spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management_system  # No spaces
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
